In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
!python --version

Python 3.9.19


1. 创建tensor

In [5]:
x = torch.rand(4,4)
x

tensor([[0.9394, 0.1650, 0.2060, 0.2899],
        [0.1699, 0.8507, 0.3837, 0.7386],
        [0.0391, 0.3592, 0.1808, 0.1385],
        [0.2703, 0.1656, 0.8787, 0.2474]])

In [6]:
x = torch.zeros(4, 4, dtype=torch.long)
x

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [7]:
x = torch.tensor([3.14,1.59])
x

tensor([3.1400, 1.5900])

In [10]:
# 获取维度信息，两种方法都可以
print(x.size())
print(x.shape)

torch.Size([2])
torch.Size([2])


2. tensor操作

In [26]:
# 加法
# 1 使用python内置加法
x = torch.rand(3,4)
y = torch.rand(3,4)
print(x)
print(y)
print(x + y)

tensor([[0.7724, 0.4498, 0.0434, 0.4108],
        [0.2852, 0.1988, 0.7160, 0.1822],
        [0.5640, 0.6897, 0.5707, 0.6149]])
tensor([[0.2941, 0.0507, 0.4964, 0.2940],
        [0.1052, 0.1320, 0.5226, 0.0297],
        [0.3483, 0.2081, 0.3229, 0.6375]])
tensor([[1.0665, 0.5005, 0.5397, 0.7049],
        [0.3904, 0.3308, 1.2386, 0.2119],
        [0.9123, 0.8978, 0.8936, 1.2524]])


In [27]:
# 2 使用torch.add函数 
print(torch.add(x, y))

tensor([[1.0665, 0.5005, 0.5397, 0.7049],
        [0.3904, 0.3308, 1.2386, 0.2119],
        [0.9123, 0.8978, 0.8936, 1.2524]])


In [28]:
# 3 原值修改
print(y.add(x)) # Attention func add() doesn't change y
print("y is not changed:\n", y)
print(y.add_(x)) # func add_() will chage the original value of y
print("y is changed:\n", y)

tensor([[1.0665, 0.5005, 0.5397, 0.7049],
        [0.3904, 0.3308, 1.2386, 0.2119],
        [0.9123, 0.8978, 0.8936, 1.2524]])
y is not changed:
 tensor([[0.2941, 0.0507, 0.4964, 0.2940],
        [0.1052, 0.1320, 0.5226, 0.0297],
        [0.3483, 0.2081, 0.3229, 0.6375]])
tensor([[1.0665, 0.5005, 0.5397, 0.7049],
        [0.3904, 0.3308, 1.2386, 0.2119],
        [0.9123, 0.8978, 0.8936, 1.2524]])
y is changed:
 tensor([[1.0665, 0.5005, 0.5397, 0.7049],
        [0.3904, 0.3308, 1.2386, 0.2119],
        [0.9123, 0.8978, 0.8936, 1.2524]])


3. inedx operation

In [30]:
x = torch.rand(3,4)
print(x)
print('\n',x[:, 1])

tensor([[0.9831, 0.0778, 0.6800, 0.3422],
        [0.6729, 0.4878, 0.5622, 0.8390],
        [0.8488, 0.7444, 0.5364, 0.1978]])

 tensor([0.0778, 0.4878, 0.7444])


索引取出来的结果和原tensor共享内存，修改是同步的

4. 维度变换

In [32]:
# torch.view, torch.reshape
x = torch.rand(4,4)
print("the original x: \n", x)
y = x.view(16)
print("change the dim of x to 16: \n", y)
z = x.view(-1,8) # -1 表示这一维度的长度由其他维度确定
print("change the dim of x to (2,8): \n", z)

the original x: 
 tensor([[0.3852, 0.6108, 0.3992, 0.8346],
        [0.7671, 0.9568, 0.6151, 0.8207],
        [0.1338, 0.7672, 0.1710, 0.2518],
        [0.6416, 0.9894, 0.5339, 0.9618]])
change the dim of x to 16: 
 tensor([0.3852, 0.6108, 0.3992, 0.8346, 0.7671, 0.9568, 0.6151, 0.8207, 0.1338,
        0.7672, 0.1710, 0.2518, 0.6416, 0.9894, 0.5339, 0.9618])
change the dim of x to (2,8): 
 tensor([[0.3852, 0.6108, 0.3992, 0.8346, 0.7671, 0.9568, 0.6151, 0.8207],
        [0.1338, 0.7672, 0.1710, 0.2518, 0.6416, 0.9894, 0.5339, 0.9618]])


torch.view会让原张量和维度变换后的张量共享内存，大部分时候，我们不希望他们之间是共享内存的
而第二种方法，`torch.reshape`，可以改变维度，但是不一定保证其返回的是其拷贝值

In [34]:
y = x.reshape(16)
y += 1
print(y)
print(x)
# 可以看到，依旧是x和y共享内存

tensor([2.3852, 2.6108, 2.3992, 2.8346, 2.7671, 2.9568, 2.6151, 2.8207, 2.1338,
        2.7672, 2.1710, 2.2518, 2.6416, 2.9894, 2.5339, 2.9618])
tensor([[2.3852, 2.6108, 2.3992, 2.8346],
        [2.7671, 2.9568, 2.6151, 2.8207],
        [2.1338, 2.7672, 2.1710, 2.2518],
        [2.6416, 2.9894, 2.5339, 2.9618]])


还有一种办法，就是使用clone拷贝一份tensor 再使用view进行维度变换

In [35]:
y = x.clone()
y += 1
print(y)
print(x)
# 可以看到y变化了，x没有发生变化

tensor([[3.3852, 3.6108, 3.3992, 3.8346],
        [3.7671, 3.9568, 3.6151, 3.8207],
        [3.1338, 3.7672, 3.1710, 3.2518],
        [3.6416, 3.9894, 3.5339, 3.9618]])
tensor([[2.3852, 2.6108, 2.3992, 2.8346],
        [2.7671, 2.9568, 2.6151, 2.8207],
        [2.1338, 2.7672, 2.1710, 2.2518],
        [2.6416, 2.9894, 2.5339, 2.9618]])


5. 取值操作，使用item可以取出tensor中的数值，但必须指定要取的值的位置，不能直接对整个tensor进行操作

In [37]:
x[1,1].item()

2.9567813873291016

In [39]:
x.item()

RuntimeError: a Tensor with 16 elements cannot be converted to Scalar

6. 广播机制
当两个tensor的形状不一致的时候，进行逐元素运算的时候，会将两个tensor的形状先变为一样，并用原值复制填充

In [40]:
x = torch.rand(1,2)
y = torch.rand(3,4)
print("x:\n",x)
print("y:\n",y)
print("x + y:\n",x + y)

x:
 tensor([[0.7231, 0.2137]])
y:
 tensor([[0.4987, 0.4809, 0.4975, 0.0572],
        [0.0105, 0.4499, 0.4689, 0.9800],
        [0.1806, 0.5032, 0.8568, 0.9174]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

可以看到这样子操作是错误的，为什么呢，请看torch中的广播机制的要求
广播机制规则
1. 如果遵守以下规则，则两个tensor是“可广播的”：

每个tensor至少有一个维度；
遍历tensor所有维度时，从末尾开始遍历（从右往左开始遍历）（从后往前开始遍历），两个tensor存在下列情况：

- tensor维度相等。
- tensor维度不等且其中一个维度为1。
- tensor维度不等且其中一个维度不存在。

2. 如果两个tensor是“可广播的”，则计算过程遵循下列规则：

- 如果两个tensor的维度不同，则在维度较小的tensor的前面增加维度，使它们维度相等。
- 对于每个维度，计算结果的维度值取两个tensor中较大的那个值。
- 两个tensor扩展维度的过程是将数值进行复制。
                        
> 原文链接：https://blog.csdn.net/flyingluohaipeng/article/details/125109094

所以需要tensor中某一维度必须为1

In [41]:
x = torch.rand(1,2)
y = torch.rand(3,1)
print("x:\n",x)
print("y:\n",y)
print("x + y:\n",x + y)

x:
 tensor([[0.4703, 0.0403]])
y:
 tensor([[0.9153],
        [0.0226],
        [0.7550]])
x + y:
 tensor([[1.3856, 0.9556],
        [0.4929, 0.0629],
        [1.2253, 0.7953]])
